version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: deployment/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deployment/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deployment/application_start.sh
      timeout: 600
      runas: root
  ValidateService:
    - location: deployment/validate_service.sh
      timeout: 300
      runas: root
